routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Protegendo rota para apenas super-admin poder acessa-la. Mais em: https://docs.spatie.be/laravel-permission/v2/basic-usage/middleware/
// Route::group(['middleware' => ['role:super-admin']], function () {
    Route::resource('/usuarios', 'UserController');
// });

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;


class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $user = Auth::user();
        // metodo implode une itens de uma colection e separa pelo caracter passado no segundo parametro
        $rol = $user->roles->implode('name', ',');

        switch ($rol) {
            case 'super-admin':
                $saudacao = "Bem-vindo Super-admin";
                return view('home', compact('saudacao'));
                break;

            case 'moderador':
            case 'super-admin':
                $saudacao = "Bem-vindo Moderador";
                return view('home', compact('saudacao'));
                break;

            case 'editor':
            case 'super-admin':
                $saudacao = "Bem-vindo Editor";
                return view('home', compact('saudacao'));
                break;
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    public function __construct()
    {
        // protegendo controllers e metodos
        //quem possui permissao create user só pode criar e 
        $this->middleware(['permission:create user'], ['only' => ['create', 'store']]);
        //quem só pode read users só vai ter acesso ao index
        $this->middleware(['permission:read users'], ['only' => 'index']);
        //quem pode editar usuario pode criar 
        $this->middleware(['permission:update user'], ['only' => ['edit', 'update']]);
        //só podera deletar
        $this->middleware(['permission:delete user'], ['only' => 'delete']);
    }




    public function index()
    {
        $users = User::all();
        return view('usuarios.index', compact('users'));
    }


    public function create()
    {
        $roles = Role::all()->pluck('name', 'id');
        return view('usuarios.create', compact('roles'));
    }


    public function store(Request $request)
    {
        $usuario = new User;

        $usuario->name = $request->name;
        $usuario->email = $request->email;
        $usuario->password = bcrypt($request->password);

        if ($usuario->save()) {
            # code...
            $usuario->assignRole($request->role);

            return redirect()->route('usuarios.index');
        }
    }




    public function edit($id)
    {
        $roles = Role::all()->pluck('name', 'id');
        $usuario = User::findOrFail($id);

        return view('usuarios.edit', compact('usuario', 'roles'));
    }


    public function update(Request $request, $id)
    {
        $usuario = User::findOrFail($id);
        $usuario->name = $request->name;
        $usuario->email = $request->email;
        //verifica se o input do password vem preenchido e atualiza
        if ($request->password != null) {
            $usuario->password = $request->password;
        }
        //substitui role antigo pelo novo
        $usuario->syncRoles($request->role);

        $usuario->save();

        return redirect()->route('usuarios.index');
    }


    public function destroy($id)
    {
        $usuario = User::findOrFail($id);

        // Excluir Role
        $usuario->removeRole($usuario->roles->implode('name', ','));
        // Excluir usuario
        if ($usuario->delete()) {
            return redirect()->route('usuarios.index');
        } else {
            return response()->json([
                'Mensagem' => 'Erro ao excluir usuário'
            ]);
        }
    }
}

resources/views/Usuarios/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h3>Novo usuário:</h3>
                </div>
                <div class="card-body">
                    <form action="{{ route('usuarios.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            Name:
                            <input type="text" name="name" class="form-control" required>
                        </div>

                        <div class="form-group">
                            Email:
                            <input type="email" name="email" class="form-control" required>
                        </div>

                        <div class="form-group">
                            Password:
                            <input type="password" name="password" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="roles">Funções</label>
                            <select class="form-control" name="role">
                                @foreach($roles as $key => $value)
                                <option value="{{ $value }}">{{ $value }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-primary " value="Enviar">
                            <a href="{{ route('usuarios.index') }}" class="btn btn-danger">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>
@endsection

resources/views/Usuarios/delete.blade.php
<form action="{{ route('usuarios.destroy', $user) }}" method="post" style="display:inline-block">
    @method('DELETE')
    @csrf
    <button type="submit" class="btn btn-danger">Excluir</button>
</form>

resources/views/Usuarios/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h3>Editando usuário:</h3>
                </div>
                <div class="card-body">
                    <form action="{{ route('usuarios.update', $usuario) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            Name:
                            <input type="text" name="name" class="form-control" value="{{ $usuario->name }}" required>
                        </div>

                        <div class="form-group">
                            Email:
                            <input type="email" name="email" class="form-control" value="{{ $usuario->email }}"  required>
                        </div>

                        <div class="form-group">
                            Password:
                            <input type="password" name="password" class="form-control" value="{{ $usuario->password }}" required>
                        </div>

                        <div class="form-group">
                            <label for="roles">Funções</label>
                            <select class="form-control" name="role">
                                @foreach($roles as $key => $value)

                                    @if($usuario->hasRole($value))
                                        <option value="{{ $value }}" selected >{{ $value }}</option>
                                    @else
                                         <option value="{{ $value }}" >{{ $value }}</option>
                                    @endif

                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-primary " value="Enviar">
                            <a href="{{ route('usuarios.index') }}" class="btn btn-danger">Cancelar</a>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>
@endsection

resources/views/Usuarios/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

            <div class="card">
                <div class="card-header">
                    <h1>Lista de usuários</h1>
                </div>
                <div class="card-body">
                    <div class="">
                        <!-- Por funcao: @can('update user')  -->
                        @role('super-admin') 
                          <a href="{{ route('usuarios.create') }}" class="btn btn-success float-right">Add user</a>
                        @else  
                          <a href="#" class="btn btn-success float-right disabled" aria-disabled="true">Add user</a>
                        @endrole   
                        <!-- Por funcao: @endcan('update user')  -->          
                    </div>
                    <table class="table">
                        <thead>
                            <th>Name: </th>
                            <th>Email: </th>
                            <th>Funções: </th>
                            <th>Actions: </th>

                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->roles->implode('name', ',') }}</td>
                                <td>
                                    @role('super-admin')
                                        <a href="{{ route('usuarios.edit', $user) }}" class="btn btn-dark">Editar</a>
                                        <!-- Inclui template contendo form com metodo delete -->
                                        @include('usuarios.delete', ['user' => $user])
                                    @else
                                        Sem ação
                                    @endrole
                                </td>

                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>

        </div>


    </div>
</div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ $saudacao }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else

                        <li>
                            <a href="{{ route('usuarios.index') }}" class="nav-link">Usuarios</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>